# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  update_biobricks_dependencies:
    cmd: uv run stages/00_update_biobricks_deps.sh
    deps:
      - stages/00_update_biobricks_deps.sh
    always_changed: true
  process: 
    cmd: uv run python3 stages/01_process.py
    deps:
      - stages/01_process.py
      - .bb/dependencies.txt
    outs:
      - cache/process/combined_relations.ttl